In [ ]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
from sklearn.metrics import accuracy_score
from sklearn.model_selection import train_test_split
import numpy as np
import pandas as pd
df = pd.read_csv('train.csv')
df.head(100)

,pclass,survived,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,boat,body,home.dest
0,1.0,1.0,"Allen, Miss. Elisabeth Walton",female,29.0000,0.0,0.0,24160.0,211.3375,B5,S,2.0,NaN,"St Louis, MO"
1,1.0,1.0,"Allison, Master. Hudson Trevor",male,0.9167,1.0,2.0,113781.0,151.5500,C22 C26,S,11,NaN,"Montreal, PQ / Chesterville, ON"
2,1.0,0.0,"Allison, Miss. Helen Loraine",female,2.0000,1.0,2.0,113781.0,151.5500,C22 C26,S,NaN,NaN,"Montreal, PQ / Chesterville, ON"
3,1.0,0.0,"Allison, Mr. Hudson Joshua Creighton",male,30.0000,1.0,2.0,113781.0,151.5500,C22 C26,S,NaN,135.0,"Montreal, PQ / Chesterville, ON"
4,1.0,0.0,"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",female,25.0000,1.0,2.0,113781.0,151.5500,C22 C26,S,NaN,NaN,"Montreal, PQ / Chesterville, ON"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,1.0,1.0,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0000,1.0,0.0,113803,53.1000,C123,S,D,NaN,"Scituate, MA"
96,1.0,1.0,"Gibson, Miss. Dorothy Winifred",female,22.0000,0.0,1.0,112378,59.4000,NaN,C,7,NaN,"New York, NY"
97,1.0,1.0,"Gibson, Mrs. Leonard (Pauline C Boeson)",female,45.0000,0.0,1.0,112378,59.4000,NaN,C,7,NaN,"New York, NY"
98,1.0,0.0,"Giglio, Mr. Victor",male,24.0000,0.0,0.0,PC 17593,79.2000,B86,C,NaN,NaN,NaN
99,1.0,1.0,"Goldenberg, Mr. Samuel L",male,49.0000,1.0,0.0,17453,89.1042,C92,C,5,NaN,"Paris, France / New York, NY"

In [ ]:
df = pd.read_csv('train.csv')

df['sex'] = df['sex'].map({'female': 1, 'male': 2})
# Xóa cột 'name'
df = df.drop(['name', 'home.dest'], axis=1)
# Thêm cột 'idpassenger' từ 0 đến cao
df['PassengerId'] = range(len(df))
df = df[['PassengerId'] + [col for col in df.columns if col != 'PassengerId']]
df['cabin'] = pd.factorize(df['cabin'])[0]
df['embarked'] = pd.factorize(df['embarked'])[0]
df['boat'] = pd.factorize(df['boat'])[0]
df['body'] = pd.factorize(df['body'])[0]
df['ticket'] = df['ticket'].str.extract('(\d+)', expand=False).astype(float).fillna(0).astype(int)
df = df.fillna(0)
df = df.reset_index(drop=True)
df.head(100)

# Chia dữ liệu thành features (X) và labels (y)
X = df.drop('survived', axis=1)  # Thay 'target_column_name' bằng tên cột chứa nhãn của bạn
y = df['survived']

# Chia dữ liệu thành tập huấn luyện và tập kiểm thử
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=1)
X_train= X_train.values
X_test= X_test.values
y_train = y_train.values
y_test = y_test.values
df.head(11111)

,PassengerId,pclass,survived,sex,age,sibsp,parch,ticket,fare,cabin,embarked,boat,body
0,0,1.0,1.0,1,29.0000,0.0,0.0,24160,211.3375,0,0,0,-1
1,1,1.0,1.0,2,0.9167,1.0,2.0,113781,151.5500,1,0,1,-1
2,2,1.0,0.0,1,2.0000,1.0,2.0,113781,151.5500,1,0,-1,-1
3,3,1.0,0.0,2,30.0000,1.0,2.0,113781,151.5500,1,0,-1,0
4,4,1.0,0.0,1,25.0000,1.0,2.0,113781,151.5500,1,0,-1,-1
...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,886,3.0,0.0,1,14.5000,1.0,0.0,2665,14.4542,-1,1,-1,79
887,887,3.0,0.0,1,0.0000,1.0,0.0,2665,14.4542,-1,1,-1,-1
888,888,3.0,0.0,2,26.5000,0.0,0.0,2656,7.2250,-1,1,-1,80
889,889,3.0,0.0,2,27.0000,0.0,0.0,2670,7.2250,-1,1,-1,-1
890,890,3.0,0.0,2,29.0000,0.0,0.0,315082,7.8750,-1,0,-1,-1

In [ ]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score



i = 0
logreg_model = LogisticRegression(penalty='l1',  solver = 'liblinear', C=0.8, max_iter=10000, random_state=1)


logreg_model.fit(X_train, y_train)
predictions = logreg_model.predict(X_test)

for i in range(len(X_test)):
    print(f"Prediction: {predictions[i]}, Actual: {y_test[i]}")

accuracy = accuracy_score(predictions, y_test)
print("Accuracy:", accuracy)

y_pred= logreg_model.predict(X_test)
precision = precision_score(y_test, y_pred, average=None)
recall = recall_score(y_test, y_pred, average = None)
f1 = f1_score(y_test, y_pred, average= None)

for class_index in range(len(precision)):
	print(f'Class { class_index}:')
	print(f'Precision: {precision[class_index]}')
	print(f'Recall: {recall[class_index]}')
	print(f'F1-score: {f1[class_index]}')
for c_value in [0.00001, 0.01, 0.1, 1, 10, 100,10000]:
    logreg_model = LogisticRegression(penalty='l2', C=c_value, max_iter=1000, random_state=1)
    logreg_model.fit(X_train, y_train)
    predictions = logreg_model.predict(X_test)
    accuracy = accuracy_score(predictions, y_test)
    print(f"C = {c_value}, Accuracy = {accuracy}")
for penalty_type in ['l1', 'l2']:
    if penalty_type == 'l1':
        solver_type = 'liblinear'  # hoặc 'saga'
    else:
        solver_type = 'lbfgs'  # hoặc chọn solver khác hỗ trợ penalty 'l2'

    logreg_model = LogisticRegression(penalty=penalty_type, solver=solver_type, C=1.0, max_iter=1000, random_state=1)
    logreg_model.fit(X_train, y_train)
    predictions = logreg_model.predict(X_test)
    accuracy = accuracy_score(predictions, y_test)
    print(f"Penalty = {penalty_type}, Solver = {solver_type}, Accuracy = {accuracy}")

Prediction: 0.0, Actual: 0.0
Prediction: 0.0, Actual: 0.0
Prediction: 0.0, Actual: 0.0
Prediction: 1.0, Actual: 1.0
Prediction: 0.0, Actual: 0.0
Prediction: 1.0, Actual: 1.0
Prediction: 0.0, Actual: 0.0
Prediction: 0.0, Actual: 0.0
Prediction: 1.0, Actual: 1.0
Prediction: 1.0, Actual: 1.0
Prediction: 0.0, Actual: 0.0
Prediction: 0.0, Actual: 0.0
Prediction: 1.0, Actual: 1.0
Prediction: 1.0, Actual: 1.0
Prediction: 0.0, Actual: 0.0
Prediction: 1.0, Actual: 1.0
Prediction: 0.0, Actual: 0.0
Prediction: 0.0, Actual: 0.0
Prediction: 1.0, Actual: 1.0
Prediction: 1.0, Actual: 1.0
Prediction: 0.0, Actual: 0.0
Prediction: 1.0, Actual: 1.0
Prediction: 1.0, Actual: 1.0
Prediction: 0.0, Actual: 0.0
Prediction: 0.0, Actual: 1.0
Prediction: 0.0, Actual: 0.0
Prediction: 0.0, Actual: 0.0
Prediction: 0.0, Actual: 0.0
Prediction: 0.0, Actual: 0.0
Prediction: 0.0, Actual: 0.0
Prediction: 1.0, Actual: 0.0
Prediction: 0.0, Actual: 0.0
Prediction: 0.0, Actual: 0.0
Prediction: 0.0, Actual: 0.0
Prediction: 0.0, Actual: 0.0
Prediction: 1.0, Actual: 1.0
Prediction: 1.0, Actual: 1.0
Prediction: 0.0, Actual: 0.0
Prediction: 1.0, Actual: 1.0
Prediction: 0.0, Actual: 0.0
Prediction: 0.0, Actual: 0.0
Prediction: 1.0, Actual: 1.0
Prediction: 0.0, Actual: 0.0
Prediction: 1.0, Actual: 1.0
Prediction: 0.0, Actual: 0.0
Prediction: 1.0, Actual: 1.0
Prediction: 0.0, Actual: 0.0
Prediction: 0.0, Actual: 0.0
Prediction: 0.0, Actual: 0.0
Prediction: 0.0, Actual: 0.0
Prediction: 1.0, Actual: 1.0
Prediction: 0.0, Actual: 0.0
Prediction: 0.0, Actual: 0.0
Prediction: 0.0, Actual: 1.0
Prediction: 0.0, Actual: 0.0
Prediction: 0.0, Actual: 0.0
Prediction: 1.0, Actual: 1.0
Prediction: 1.0, Actual: 1.0
Prediction: 1.0, Actual: 1.0
Prediction: 1.0, Actual: 1.0
Prediction: 1.0, Actual: 1.0
Prediction: 0.0, Actual: 0.0
Prediction: 0.0, Actual: 0.0
Prediction: 1.0, Actual: 1.0
Prediction: 0.0, Actual: 0.0
Prediction: 0.0, Actual: 0.0
Prediction: 0.0, Actual: 0.0
Prediction: 0.0, Actual: 0.0
Prediction: 1.0, Actual: 1.0
Prediction: 0.0, Actual: 0.0
Prediction: 0.0, Actual: 0.0
Prediction: 0.0, Actual: 0.0
Prediction: 0.0, Actual: 0.0
Prediction: 0.0, Actual: 0.0
Prediction: 0.0, Actual: 0.0
Prediction: 0.0, Actual: 0.0
Prediction: 1.0, Actual: 1.0
Prediction: 0.0, Actual: 0.0
Prediction: 0.0, Actual: 0.0
Prediction: 0.0, Actual: 0.0
Prediction: 0.0, Actual: 0.0
Prediction: 0.0, Actual: 0.0
Prediction: 0.0, Actual: 0.0
Prediction: 0.0, Actual: 0.0
Prediction: 0.0, Actual: 0.0
Prediction: 0.0, Actual: 0.0
Prediction: 1.0, Actual: 1.0
Prediction: 0.0, Actual: 0.0
Prediction: 0.0, Actual: 0.0
Prediction: 1.0, Actual: 1.0
Prediction: 0.0, Actual: 0.0
Prediction: 0.0, Actual: 0.0
Prediction: 0.0, Actual: 0.0
Prediction: 1.0, Actual: 1.0
Prediction: 0.0, Actual: 0.0
Prediction: 0.0, Actual: 0.0
Prediction: 0.0, Actual: 0.0
Prediction: 1.0, Actual: 1.0
Prediction: 0.0, Actual: 0.0
Prediction: 0.0, Actual: 0.0
Prediction: 1.0, Actual: 1.0
Prediction: 0.0, Actual: 0.0
Prediction: 1.0, Actual: 1.0
Prediction: 0.0, Actual: 1.0
Prediction: 0.0, Actual: 0.0
Prediction: 0.0, Actual: 0.0
Prediction: 1.0, Actual: 1.0
Prediction: 0.0, Actual: 0.0
Prediction: 1.0, Actual: 1.0
Prediction: 0.0, Actual: 0.0
Prediction: 1.0, Actual: 1.0
Prediction: 1.0, Actual: 1.0
Prediction: 0.0, Actual: 0.0
Prediction: 0.0, Actual: 0.0
Prediction: 0.0, Actual: 0.0
Prediction: 0.0, Actual: 0.0
Prediction: 1.0, Actual: 1.0
Prediction: 1.0, Actual: 1.0
Prediction: 0.0, Actual: 0.0
Prediction: 0.0, Actual: 0.0
Prediction: 0.0, Actual: 0.0
Prediction: 0.0, Actual: 0.0
Prediction: 1.0, Actual: 1.0
Prediction: 1.0, Actual: 1.0
Prediction: 0.0, Actual: 0.0
Prediction: 0.0, Actual: 0.0
Prediction: 0.0, Actual: 0.0
Prediction: 0.0, Actual: 0.0
Prediction: 1.0, Actual: 1.0
Prediction: 0.0, Actual: 0.0
Prediction: 0.0, Actual: 0.0
Prediction: 0.0, Actual: 0.0
Prediction: 0.0, Actual: 0.0
Prediction: 0.0, Actual: 0.0
Prediction: 1.0, Actual: 1.0
Prediction: 1.0, Actual: 1.0
Prediction: 1.0, Actual: 1.0
Prediction: 0.0, Actual: 0.0
Prediction: 0.0, Actual: 0.0
Prediction: 0.0, Actual: 0.0
Prediction: 0.0, Actual: 0.0
Prediction: 0.0, Actual: 0.0
Prediction: 0.0, Actual: 0.0
Prediction: 1.0, Actual: 1.0
Prediction: 0.0, Actual: 0.0
Prediction: 1.0, Actual: 1.0
Prediction: 0.0, Actual: 1.0
Prediction: 1.0, Actual: 0.0
Prediction: 0.0, Actual: 0.0
Prediction: 0.0, Actual: 0.0
Prediction: 0.0, Actual: 0.0
Prediction: 0.0, Actual: 0.0
Prediction: 1.0, Actual: 1.0
Prediction: 1.0, Actual: 1.0
Prediction: 0.0, Actual: 0.0
Prediction: 0.0, Actual: 0.0
Prediction: 0.0, Actual: 0.0
Prediction: 1.0, Actual: 1.0
Prediction: 0.0, Actual: 0.0
Prediction: 0.0, Actual: 0.0
Prediction: 1.0, Actual: 1.0
Prediction: 1.0, Actual: 1.0
Prediction: 1.0, Actual: 1.0
Prediction: 0.0, Actual: 0.0
Prediction: 1.0, Actual: 1.0
Prediction: 0.0, Actual: 0.0
Prediction: 1.0, Actual: 1.0
Prediction: 1.0, Actual: 1.0
Prediction: 0.0, Actual: 0.0
Prediction: 0.0, Actual: 0.0
Prediction: 0.0, Actual: 0.0
Prediction: 1.0, Actual: 1.0
Prediction: 1.0, Actual: 1.0
Prediction: 0.0, Actual: 0.0
Prediction: 0.0, Actual: 0.0
Prediction: 0.0, Actual: 0.0
Prediction: 1.0, Actual: 1.0
Prediction: 0.0, Actual: 0.0
Prediction: 0.0, Actual: 0.0
Accuracy: 0.9664804469273743
Class 0:
Precision: 0.9663865546218487
Recall: 0.9829059829059829
F1-score: 0.9745762711864406
Class 1:
Precision: 0.9666666666666667
Recall: 0.9354838709677419
F1-score: 0.9508196721311476
C = 1e-05, Accuracy = 0.7206703910614525
C = 0.01, Accuracy = 0.9608938547486033
C = 0.1, Accuracy = 0.9608938547486033
C = 1, Accuracy = 0.9608938547486033
C = 10, Accuracy = 0.9608938547486033
C = 100, Accuracy = 0.9608938547486033
C = 10000, Accuracy = 0.9608938547486033
Penalty = l1, Solver = liblinear, Accuracy = 0.9664804469273743
Penalty = l2, Solver = lbfgs, Accuracy = 0.9608938547486033

In [ ]:
dd = pd.read_csv('test.csv')

dd['sex'] = dd['sex'].map({'female': 1, 'male': 2})
# Xóa cột 'name'
dd = dd.drop(['name', 'home.dest'], axis=1)
# Thêm cột 'idpassenger' từ 0 đến cao
dd['PassengerId'] = range(len(dd))
dd = dd[['PassengerId'] + [col for col in dd.columns if col != 'PassengerId']]
dd['cabin'] = pd.factorize(dd['cabin'])[0]
dd['embarked'] = pd.factorize(dd['embarked'])[0]
dd['boat'] = pd.factorize(dd['boat'])[0]
dd['body'] = pd.factorize(dd['body'])[0]
dd['ticket'] = dd['ticket'].str.extract('(\d+)', expand=False).astype(float).fillna(0).astype(int)
dd = dd.fillna(0)

dd = dd.reset_index(drop=True)
dd.head(400)
test_Y_pred = logreg_model.predict(dd)

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:432: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  warnings.warn(

In [ ]:
import pandas as pd

# Giả sử test_Y_pred chứa các giá trị dự đoán từ mô hình Logistic Regression
# dd chứa dữ liệu từ file test.csv

# Tạo DataFrame mới từ giá trị dự đoán
result_df = pd.DataFrame({'survived': test_Y_pred})

# Hiển thị DataFrame mới

# Giả sử dd chứa dữ liệu từ file test.csv và có cột "PassengerId"
# Kết hợp cột "PassengerId" với DataFrame kết quả
result_df['PassengerId'] = dd['PassengerId']
result_df = result_df.reset_index(drop=True)
# Hiển thị DataFrame mới sau khi kết hợp
result_df = result_df[['PassengerId', 'survived']]

print(result_df)
result_df.to_csv('sample_submission.csv', index=False)

     PassengerId  survived
0              0       0.0
1              1       0.0
2              2       0.0
3              3       0.0
4              4       0.0
..           ...       ...
413          413       0.0
414          414       1.0
415          415       0.0
416          416       0.0
417          417       1.0

[418 rows x 2 columns]

In [ ]:
train_data = pd.read_csv('train.csv')
train_data.head()

,pclass,survived,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,boat,body,home.dest
0,1.0,1.0,"Allen, Miss. Elisabeth Walton",female,29.0000,0.0,0.0,24160.0,211.3375,B5,S,2.0,NaN,"St Louis, MO"
1,1.0,1.0,"Allison, Master. Hudson Trevor",male,0.9167,1.0,2.0,113781.0,151.5500,C22 C26,S,11,NaN,"Montreal, PQ / Chesterville, ON"
2,1.0,0.0,"Allison, Miss. Helen Loraine",female,2.0000,1.0,2.0,113781.0,151.5500,C22 C26,S,NaN,NaN,"Montreal, PQ / Chesterville, ON"
3,1.0,0.0,"Allison, Mr. Hudson Joshua Creighton",male,30.0000,1.0,2.0,113781.0,151.5500,C22 C26,S,NaN,135.0,"Montreal, PQ / Chesterville, ON"
4,1.0,0.0,"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",female,25.0000,1.0,2.0,113781.0,151.5500,C22 C26,S,NaN,NaN,"Montreal, PQ / Chesterville, ON"

In [ ]:

train_data.head(1000)

,pclass,survived,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,boat,body,home.dest
0,1.0,1.0,"Allen, Miss. Elisabeth Walton",female,29.0000,0.0,0.0,24160.0,211.3375,B5,S,2.0,NaN,"St Louis, MO"
1,1.0,1.0,"Allison, Master. Hudson Trevor",male,0.9167,1.0,2.0,113781.0,151.5500,C22 C26,S,11,NaN,"Montreal, PQ / Chesterville, ON"
2,1.0,0.0,"Allison, Miss. Helen Loraine",female,2.0000,1.0,2.0,113781.0,151.5500,C22 C26,S,NaN,NaN,"Montreal, PQ / Chesterville, ON"
3,1.0,0.0,"Allison, Mr. Hudson Joshua Creighton",male,30.0000,1.0,2.0,113781.0,151.5500,C22 C26,S,NaN,135.0,"Montreal, PQ / Chesterville, ON"
4,1.0,0.0,"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",female,25.0000,1.0,2.0,113781.0,151.5500,C22 C26,S,NaN,NaN,"Montreal, PQ / Chesterville, ON"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,3.0,0.0,"Zabour, Miss. Hileni",female,14.5000,1.0,0.0,2665,14.4542,NaN,C,NaN,328.0,NaN
887,3.0,0.0,"Zabour, Miss. Thamine",female,NaN,1.0,0.0,2665,14.4542,NaN,C,NaN,NaN,NaN
888,3.0,0.0,"Zakarian, Mr. Mapriededer",male,26.5000,0.0,0.0,2656,7.2250,NaN,C,NaN,304.0,NaN
889,3.0,0.0,"Zakarian, Mr. Ortin",male,27.0000,0.0,0.0,2670,7.2250,NaN,C,NaN,NaN,NaN
890,3.0,0.0,"Zimmerman, Mr. Leo",male,29.0000,0.0,0.0,315082,7.8750,NaN,S,NaN,NaN,NaN